### ISSUE TITLE
The data format of the example seems to be wrong

### ISSUE THREAD

**Issue by LongHZ140516** [ShijieZhou-UCLA/DreamScene360#1]
Thank you very much for allowing me to experience this impressive work. I have tried running the code, and the results are excellent! However, there seems to be a minor issue that might be worth addressing, although it is not particularly critical.

In `scene/__init__`, the load_data function seems to have three conditional checks for loading data:

- `if os.path.exists(os.path.join(args.source_path, "sparse")):`

- `os.path.exists(os.path.join(args.source_path, "transforms_train.json"))`

- `any(filename.endswith('.png') for filename in os.listdir(args.source_path)) or any(filename.endswith('.txt') for filename in os.listdir(args.source_path))`

However, the example in `data/alley_pano` appears to contain images in `.jpg` format, which causes it to not run directly. For future users' experience and ease of experimentation, perhaps the format in the example could be adjusted. This is just a minor issue, and your code's results are truly impressive. Thank you once again for your amazing work.

**Comment by ShijieZhou-UCLA** [comment]
Hi @LongHZ140516! Thank you so much for bringing this up, I have just fixed it! I appreciate your kind words, and hope our code could be helpful for your project!

Best,
Shijie
